version: '3'
services:
  session_kicker:
    container_name: session_kicker
    image: wardpearce/session-kicker
    restart: unless-stopped
    ports:
      - "8887:80"
    environment:
      JELLYFIN_API_KEY: ""
      JELLYFIN_API_URL: ""

      DONT_KICK_ITEM_TYPE: "movie"
      CHECK_DELAY_IN_SECONDS: 10.0
      MESSAGE_TIME_IN_MILLI: 60000
      MAX_WATCH_TIME_IN_SECONDS: 50.0

      # Leave blank to disable
      ITEM_ID_ON_SESSION_KICKED: ""

      WATCH_TIME_OVER_MSG: "You have used up your watch time."
      NOT_WHITELISTED_MSG: "You aren't whitelisted for unlimited watch time."

      RESET_AFTER_IN_HOURS: 24.0

      HTTP_HOST: "session_kicker"
      HTTP_PORT: 80

      MONGO_DB: "session_timer"
      MONGO_HOST: "session_kicker_mongo"
      MONGO_PORT: 8886

    depends_on:
      - session_kicker_mongo
    networks:
      - backend

  session_kicker_mongo:
    image: mongo
    container_name: session_kicker_mongo
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - session_kicker_mongo_data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  session_kicker_mongo_data:
    driver: local
